
export class Constants {
	
	REQUEST_STATUS_PENDING = 1;
	REQUEST_STATUS_DECLINED = 2;	
	REQUEST_STATUS_ACCEPTED = 3;
	REQUEST_STATUS_COMPLETED = 4;
	REQUEST_STATUS_CANCELLED = 5;
	REQUEST_STATUS_NOT_COMPLETED = 6;
	REQUEST_STATUS_RESOLVED_BUT_DISPUTED = 7;
	REQUEST_STATUS_DELETED = 8;

	INCOMING = "incoming";
	OUTGOING = "outgoing"

}
