
export class Constants {
	
	REQUEST_STATUS_PENDING = 1;
	REQUEST_STATUS_DECLINED = 2;	
	REQUEST_STATUS_ACCEPTED = 3;
	REQUEST_STATUS_COMPLETED = 4;
	REQUEST_STATUS_CANCELLED = 5;
	REQUEST_STATUS_NOT_COMPLETED = 6;
	REQUEST_STATUS_RESOLVED_BUT_DISPUTED = 7;
	REQUEST_STATUS_DELETED = 8;
	REQUEST_STATUS_REQUESTOR_ACKNOWLEDGED = 9;

	INCOMING = "incoming";
	OUTGOING = "outgoing";

	FUNCTION_KEY_PRM_REQUIRES_RECOMMENDATIONS = 0;
	FUNCTION_KEY_USER_HAS_PREVIOUSLY_REQUESTED_PRM = 1;
	FUNCTION_KEY_USER_IS_PAST_REQUEST_AGAIN_DATE = 2;
	FUNCTION_KEY_USER_HAS_NECESSARY_RECOMMENDATIONS = 3;
	FUNCTION_KEY_USER_HAS_CURRENTLY_REQUESTED_PRM = 4;
	FUNCTION_KEY_USER_HAS_SUFFICIENT_POINTS = 5;
	FUNCTION_KEY_PRM_IS_REQUESTABLE = 6;

	FUNCTION_KEY_REQUEST_IS_IN_PROGRESS = 0;
}
